### ISSUE TITLE
Assessment job not started due to error: Max number of parallel assessments reached 

### ISSUE THREAD

**Issue by dirar** [pnp/pnpassessment#60] opened 2024-06-12 12:01 UTC
Hello,

I am getting the below error when trying to run the assessments:

Assessment job not started due to error: Max number of parallel assessments reached 

The command I am running:

`
& '.\microsoft365-assessment (1).exe' start --mode AddInsACS --authmode application --tenant tenant.sharepoint.com --applicationid abceefabceef-abceef-abceef-abceef-abceefabceefabceef --certpath "My|CurrentUser|a1328739879sdsjdh289372983kjsa" 
`

I tried to add --threads 1 or --threads 5 or any number but without any success. We have 1185 sites, but also when running the command for 1 site I get the same result

Any Ideas please? 

Thanks

**Comment by jansenbe** [comment] 2024-06-12 13:13
@dirar / @oalfatyan : what version are you using? What's the OS you're running the assessment from?

**Comment by oalfatyan** [comment] 2024-06-13 04:57
we are running the latest version 1.9.0 on windows 11, it is discovering 1181 sites and it fails immediately, is it due to a threshold by Microsoft? even changing the Thread option does not help

**Comment by oalfatyan** [comment] 2024-06-13 05:11
and when tried to run the tool on a windows server 2019 I get this error:  Assessment job not started due to error: Microsoft Graph service exception
![image](https://github.com/pnp/pnpassessment/assets/55826797/6c8a4e92-7809-449f-8b21-72ac3c70226e)

**Comment by oalfatyan** [comment] 2024-06-13 07:30
The app permission is correct, also when I try to run it as interactive mode and with one site instead of tenant ...I get the same error
![image](https://github.com/pnp/pnpassessment/assets/55826797/54319e70-bddb-448c-8f03-462897fe3326)
![image](https://github.com/pnp/pnpassessment/assets/55826797/b665c51a-05c5-43ed-a4fd-f52b0198208e)

not sure how to proceed with this!

**Comment by jansenbe** [comment] 2024-06-13 08:22
@dirar : can you verify all microsoft365-assessment.exe processes are killed and then run below and share output:

![image](https://github.com/pnp/pnpassessment/assets/7451219/81134fdd-4dcd-4a0a-8d4c-f3e8c9727340)

**Comment by oalfatyan** [comment] 2024-06-13 08:26
![image](https://github.com/pnp/pnpassessment/assets/55826797/361e9e88-4c18-4d6b-a07b-59d00418f69f)
as requested

**Comment by jansenbe** [comment] 2024-06-13 08:31
can you copy the log output gathered in the folder where the exe file is and send it to bjansen@microsoft.com. The logs should tell us more about why you see the graph exception

**Comment by jansenbe** [comment] 2024-06-13 10:17
closing this one, root cause was missing Application.Read.All permission and not missing to provide the application id argument on the command line.

![image](https://github.com/pnp/pnpassessment/assets/7451219/b8bc6b2d-6dc6-4635-a77b-35e17e9f9e2e)

![image](https://github.com/pnp/pnpassessment/assets/7451219/116bb8eb-ae46-4c63-8b1f-22b8ac27471c)

**Closed by jansenbe** 2024-06-13 10:17 UTC
Labels: question

**Comment by dirar** [comment] 2024-06-13 10:34
@jansenbe  Thank you
